# Generated by Django 6.0 on 2025-12-22 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_exerciselog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('bedtime', models.TimeField()),
                ('wake_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('quality_score', models.IntegerField(default=0)),
                ('deep_sleep_minutes', models.IntegerField(default=0)),
                ('light_sleep_minutes', models.IntegerField(default=0)),
                ('rem_sleep_minutes', models.IntegerField(default=0)),
                ('awake_minutes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
