# Generated by Django 6.0 on 2025-12-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sleeplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reminders_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
